version: 2

models:

  - name: mart_sales_by_state_m_y
    description: |
      Monthly sales performance by state.  
      - Defaults to the last 3 years of data for dashboard responsiveness.  
      - Exposes `year` so users can slice any calendar year (2018–2023).
    tests:
      - not_null: {column_name: month}
      - not_null: {column_name: year}
      - not_null: {column_name: state_key}
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [month, year, state_key]
    columns:
      - name: month
        description: The first day of the calendar month (time grain).
      - name: year
        description: Calendar year extracted from `month`.
      - name: state_key
        description: Two-digit FIPS code for the state (matches `dim_state.state_fips`).
      - name: orders_count
        description: Number of orders in that state/month.
      - name: total_revenue
        description: Sum of `order_value` for that state/month.
      - name: avg_order_value
        description: Average order value for that state/month.

  - name: mart_sales_by_category_m_y
    description: |
      Monthly sales performance by product category.  
      - Defaults to the last 3 years of data.  
      - Exposes `year` for full-history filtering.
    tests:
      - not_null: {column_name: month}
      - not_null: {column_name: year}
      - not_null: {column_name: category}
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [month, year, category]
    columns:
      - name: month
        description: The first day of the calendar month.
      - name: year
        description: Calendar year extracted from `month`.
      - name: category
        description: Product category (e.g. “Books”, “Electronics”).
      - name: orders_count
        description: Number of orders for that category/month.
      - name: total_revenue
        description: Sum of `order_value` for that category/month.
      - name: avg_order_value
        description: Average order value for that category/month.

  - name: mart_customer_segment_metrics
    description: |
      Aggregate metrics by customer demographic segment:
      age, income, Hispanic flag, household size.
    tests:
      - not_null: {column_name: age_group}
      - not_null: {column_name: income_bracket}
    columns:
      - name: age_group
        description: User age bracket (e.g. “25–34”).
      - name: income_bracket
        description: Household income bracket.
      - name: is_hispanic
        description: Hispanic/Latino flag.
      - name: household_size_cat
        description: Household size category.
      - name: segment_users
        description: Distinct users in the segment.
      - name: segment_revenue
        description: Sum of order_value in the segment.
      - name: avg_order_value
        description: Average order value in the segment.
      - name: avg_orders_per_user
        description: Average orders per user in the segment.

  - name: mart_cohort_retention
    description: >
      Cohort retention view showing how many users placed orders after their first purchase month,
      including retention percentage and cohort size.
    columns:
      - name: cohort_month
        description: First day of the month when the cohort started.
        tests:
          - not_null

      - name: cohort_year
        description: Year extracted from the cohort_date_key.

      - name: months_after
        description: Number of months after the initial cohort month.

      - name: active_users
        description: Number of unique users active in the given month.
        tests:
          - not_null

      - name: cohort_size
        description: Total number of users in the cohort (month 0).
        tests:
          - not_null

      - name: retention_pct
        description: Percentage of users retained (active / cohort size * 100), rounded to 1 decimal place.

  - name: mart_top_products
    description: |
      Top 50 products by revenue and units sold.
    tests:
      - not_null: {column_name: product_key}
    columns:
      - name: product_key
        description: ASIN/ISBN code (coalesced to 'UNKNOWN' if missing).
      - name: units_sold
        description: Total quantity sold.
      - name: total_revenue
        description: Sum of order_value for that product.

  - name: mart_revenue_by_income_state
    description: |
      Revenue and order count cross-tabbed by income bracket and state.
    tests:
      - not_null: {column_name: income_bracket}
      - not_null: {column_name: state_key}
    columns:
      - name: income_bracket
        description: Household income bracket.
      - name: state_key
        description: Two-digit state FIPS code.
      - name: orders_count
        description: Number of orders in that segment.
      - name: total_revenue
        description: Sum of order_value in that segment.

  - name: mart_revenue_vs_income_state_year
    description: >
      Aggregates total revenue and orders per state and year, enriched with median household income
      and population data from U.S. Census. Used to analyze correlations between economic indicators
      and purchasing behavior.

    columns:
      - name: state_name
        description: Full name of the U.S. state.

      - name: state_fips
        description: FIPS code representing the U.S. state.

      - name: year
        description: The calendar year of the data (from order date and demographic survey).

      - name: total_revenue
        description: Total revenue generated from all orders in that state and year.

      - name: total_orders
        description: Total number of orders placed in that state and year.

      - name: median_household_income
        description: Median household income for that state and year, sourced from U.S. Census API.

      - name: total_population
        description: Total population of the state for that survey year.