models:
  - name: dim_state
    description: |
      Canonical state dimension mapping postal↔name↔fips.
    tests:
      - unique:
          column_name: postal_code
      - not_null:
          column_name: postal_code

    columns:
      - name: postal_code
        description: USPS two-letter code (e.g. CA, NY)
      - name: state_name
        description: Full state name (e.g. California)
        tests: [not_null]
      - name: state_fips
        description: Two-character FIPS code (e.g. 06)
        tests: [not_null]